version: 0.0.{build}
image: 
- Visual Studio 2017 Preview
- ubuntu
install:
- sh: printf "Commands with sh Prefix run on Linux image only"
- sh: sudo apt-get update
- sh: sudo apt-get install dotnet-sdk-2.1.300-preview2-008533 -y
- sh: sudo apt-get install dotnet-runtime-2.1.0-rc1 -y
- sh: dotnet tool install coveralls.net --version 1.0.0-beta0003 --tool-path tools
- cmd: echo "Commands with cmd Prefix run on Windows image only"
- cmd: dotnet tool install coveralls.net --version 1.0.0-beta0003 --tool-path tools
build_script:
- ps: dotnet --info
- cmd: .\tools\csmacnz.Coveralls.exe --help
- sh: ./tools/csmacnz.Coveralls --help
